In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import math
from scipy.optimize import minimize
from scipy.spatial import ConvexHull
from scipy.linalg import norm
from scipy.optimize import minimize_scalar

data = pd.read_csv("banana.csv", sep=',')

In [2]:
#Normalizing the variables to values in [-1,1]
for col in data.columns:
    if col != 'Class':
        min_val = data[col].min()
        max_val = data[col].max()
        data[col] = (data[col] - min_val) / (max_val - min_val)  # Normalize to range 0-1
        data[col] = data[col] * 2 - 1  # Rescale to range -1 to 1

In [3]:
data

At1       At2  Class
0     0.433898 -0.184229     -1
1    -0.467797 -0.555556      1
2    -0.308475  0.114695     -1
3    -0.263051 -0.001075      1
4    -0.322034  0.013262      1
...        ...       ...    ...
5295  0.161017  0.354839      1
5296 -0.528814 -0.347312      1
5297  0.942373  0.265233      1
5298  0.308136  0.133333     -1
5299 -0.038983 -0.194265      1

[5300 rows x 3 columns]

In [4]:
#Data preparation 
train_data, test_data = train_test_split(data, test_size=0.2, random_state=123)
X_train = train_data.drop('Class', axis=1)
y_train = train_data['Class']

X_test = test_data.drop('Class', axis=1)
y_test = test_data['Class']

In [5]:
y_train

3887    1
2852   -1
3519    1
4798    1
3176   -1
       ..
5218   -1
4060   -1
1346   -1
3454   -1
3582    1
Name: Class, Length: 4240, dtype: int64

In [ ]:
from sklearn.tree import DecisionTreeClassifier, export_text


# Creazione di un albero decisionale
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X_train, y_train)

# Estrai le regole di decisione
regole = export_text(tree, feature_names=['Attributo A', 'Attributo B'])

# Stampa le regole
print("Regole di decisione:")
print(regole)

# Estrai le ipotesi
ipotesi = [line.strip() for line in regole.split('\n') if 'class:' in line]

# Stampa il set di ipotesi
print("\nSet di ipotesi:")
for idx, ipotesi_single in enumerate(ipotesi):
    print(f"Ipotesi {idx + 1}: {ipotesi_single}")


In [8]:
n

14

In [9]:
from sklearn.tree import DecisionTreeClassifier
import numpy as np

# Creazione di un albero decisionale
tree = DecisionTreeClassifier(max_depth=2)
tree.fit(X_train, y_train)

# Ottieni la matrice di regole di decisione (A)
regole_matrice = tree.tree_.threshold.reshape(-1, 1)

# Stampa la matrice di regole di decisione
print("Matrice di regole di decisione:")
print(regole_matrice)
m = X_train.shape[0]
n = len(regole_matrice)
#A = np.zeros((m, n))
#for i, valore in enumerate(regole_matrice):
    #A[:, i] = y_train * X_train[:, 0] * valore
    #A[:, i + len(regole_matrice)] =y_train * X_train[:, 1] * valore

Matrice di regole di decisione:
[[ 0.07150538]
 [-0.44767025]
 [-2.        ]
 [-2.        ]
 [ 0.5440678 ]
 [-2.        ]
 [-2.        ]]


In [166]:
X_train_array = X_train.values

In [59]:
import numpy as np

# Numero di righe nei dati di test
n_righe = X_train.shape[0]

# Numero di regole
n_regole = 7

# Matrice per memorizzare le previsioni per ogni riga e regola
previsioni_totali = np.zeros((n_righe, n_regole))

# Calcola le previsioni per ciascuna riga e ciascuna regola
for i in range(n_regole):
    previsioni_totali[:, i] = tree.predict(X_train_array * regole_matrice[i])

print("Previsioni totali:")
print(previsioni_totali)


Previsioni totali:
[[ 1.  1. -1. ... -1. -1. -1.]
 [ 1.  1. -1. ... -1. -1. -1.]
 [ 1. -1. -1. ... -1. -1. -1.]
 ...
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 [ 1. -1. -1. ...  1. -1. -1.]]


C:\Users\matteo posenato\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\matteo posenato\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\matteo posenato\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\matteo posenato\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\matteo posenato\anaconda3\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
C:\Users\m

In [60]:
previsioni_totali = pd.DataFrame(previsioni_totali)

In [61]:
A2 = previsioni_totali

In [62]:
A2

0    1    2    3    4    5    6
0     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
1     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
2     1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
3     1.0 -1.0  1.0  1.0  1.0  1.0  1.0
4     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
...   ...  ...  ...  ...  ...  ...  ...
4235  1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
4236  1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
4237  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4238  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4239  1.0 -1.0 -1.0 -1.0  1.0 -1.0 -1.0

[4240 rows x 7 columns]

In [167]:
print(X_train[0][1])

KeyError: 0

In [168]:
print(A)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [169]:
regole_matrice[1]

array([-0.44767025])

In [170]:
regole_matrice
a = X_train[0][:] * regole_matrice[0]
print(a)

KeyError: 0

In [63]:
def weak_learner(X, y, w):
    # Define and train the weak learner
    clf = DecisionTreeClassifier(max_depth=2)
    clf.fit(X, y,sample_weight=w)
    return clf

In [64]:
#Train the weak learner : decision tree of max depth 2 
weak_classifier = weak_learner(X_train, y_train,1)
y_pred_weak = weak_classifier.predict(X_test)
print("Predictions:", y_pred_weak)

Predictions: [-1 -1 -1 ... -1  1 -1]


In [ ]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
m, n = X_train.shape
A = np.zeros((m, n))
X_train = np.array(X_train)
y_train = np.array(y_train)
for i in range(m):
    # Get the i-th training example
    xi = X_train[i]
    yi = y_train[i]

    # Compute the prediction of the weak classifier for xi
    prediction = weak_classifier.predict([xi])

    # Assign the product of yi and the prediction to the corresponding element in A
    A[i, :] = yi * prediction

In [ ]:
A=pd.DataFrame(A)

In [ ]:
A

In [ ]:
A[0]=A[0].astype(int)
A[1]=A[1].astype(int)

In [65]:
#set d0
d0 = np.zeros(m)
for i in range(m):
    d0[i] = 1/m 

In [66]:
len(d0)

4240

In [67]:
#sendo d0 to the weak learner to obtain hj_1
h= weak_learner(X_train,y_train,d0)
hj_1 = h.tree_.threshold.reshape(-1, 1)


In [68]:
len(hj_1)

7

In [69]:
regole_matrice_1

NameError: name 'regole_matrice_1' is not defined

In [ ]:
A

In [ ]:
A1 = np.zeros((m, len(hj_1)))

In [ ]:
A1[0,:] = prediction

In [ ]:
A1

In [70]:
def encode_hypothesis(hypothesis, num_hypotheses):
    encoded_vector = np.zeros(num_hypotheses)
    encoded_vector[hypothesis] = 1
    return encoded_vector

hj_1_index = np.argmax(hj_1)  # Find the index of the predicted hypothesis
num_hypotheses = len(hj_1)  # Total number of hypotheses in the set H

ej1 = encode_hypothesis(hj_1_index, num_hypotheses)
print(ej1)

[0. 0. 0. 0. 1. 0. 0.]


In [ ]:
ej1.size

In [ ]:
m

In [ ]:
n

In [71]:
w = np.zeros(m,)
w=ej1

In [72]:
w

array([0., 0., 0., 0., 1., 0., 0.])

In [117]:
def delta(d):
    m = len(d)
    return np.sum(d * np.log(d)) + np.log(m)

def expression(d):
    return np.dot(d.T, np.dot(A2, w)) + (1/n) * delta(d)

def minimize_expression(A2, w_1, n, v):
    m = A2.shape[0]  # Numero di righe nella matrice A
    P_m_v = np.random.rand(m) / v  # Generazione casuale di d in [0, 1/v]^m (ad esempio)
    best_d = None
    min_value = float('inf')
    for _ in range(m):  # Prova vari valori casuali di d
        d = P_m_v / np.sum(P_m_v)  # Normalizza per rispettare Σₖ dₖ¹ = 1
        value = expression(d)
        
        if value < min_value:
            min_value = value
            best_d = d

    return d, best_d

In [118]:
v = 100


In [119]:
d, result = minimize_expression(A2, w, n, v)

In [76]:
len(d), len(result), len(d0)

(4240, 4240, 4240)

In [80]:
#obtain the hypotesis hj t+1 
h2= weak_learner(X_train,y_train,result)
hj_2 = h2.tree_.threshold.reshape(-1, 1)

In [81]:
hj_2

array([[ 0.01415771],
       [-0.45035842],
       [-2.        ],
       [-2.        ],
       [ 0.54745764],
       [-2.        ],
       [-2.        ]])

In [172]:
hj_2_index = np.argmax(hj_2)  # Find the index of the predicted hypothesis
num_hypotheses = len(hj_2)  # Total number of hypotheses in the set H

ej2 = encode_hypothesis(hj_2_index, num_hypotheses)
print(type(ej1))
print(type(ej2))
print(w)
print(A2)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0. 0. 0. 0. 1. 0. 0.]
        0    1    2    3    4    5    6
0     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
1     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
2     1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0
3     1.0 -1.0  1.0  1.0  1.0  1.0  1.0
4     1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
...   ...  ...  ...  ...  ...  ...  ...
4235  1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
4236  1.0  1.0 -1.0 -1.0 -1.0 -1.0 -1.0
4237  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4238  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4239  1.0 -1.0 -1.0 -1.0  1.0 -1.0 -1.0

[4240 rows x 7 columns]


In [152]:
#compute the FW weight
lamb= []
value_0 = np.dot(A2, (ej2-w))
print("value0 is: {}".format(value_0))
value_1 = np.dot(result.T, value_0)
print("value1 is: {}".format(value_1))
value_2 = np.dot(A2, (ej2 - w))
print("value2 is: {}".format(value_2))
value_3 = norm(value_2, ord=np.inf)
print("value3 is: {}".format(value_3))
value = value_1 / value_3
print("value is: {}".format(value))
lamb.insert(0, np.clip(value, 0, 1))
print("lamb is: {}".format(lamb))
w_1= []
r = (ej2 - w)
print("r is: {}".format(r))
w_1 = w + (lamb*r)
print("w_1 is: {}".format(w_1))

value0 is: [0. 0. 0. ... 0. 0. 0.]
value1 is: 0.0
value2 is: [0. 0. 0. ... 0. 0. 0.]
value3 is: 0.0
value is: nan
lamb is: [nan]
r is: [0. 0. 0. 0. 0. 0. 0.]
w_1 is: [nan nan nan nan nan nan nan]


C:\Users\matteo posenato\AppData\Local\Temp\ipykernel_12588\1028861585.py:11: RuntimeWarning: invalid value encountered in scalar divide
  value = value_1 / value_3


In [101]:

def secondary_weight(A, d, w):
    return np.dot(d.T, np.dot(A, w))
def objective_function(d):
        return secondary_weight(A2, d, w)

def minimize_secondary_weight(A, w):
    m = A.shape[0]
    best_d = None
    min_value = float('inf')

    for _ in range(m):
        value = objective_function(d)
        if value < min_value:
            min_value = value
            best_d = d

    return best_d, min_value
result_d, result_value = minimize_secondary_weight(A2, w)
print("Vettore d ottimale:", result_d)
print("Valore minimo:", result_value)


Vettore d ottimale: [5.51040843e-05 1.23241849e-04 7.41805742e-05 ... 1.13072830e-04
 1.38732425e-04 2.16363394e-04]
Valore minimo: 0.47819370864332117


In [112]:
#update the weight
w_2 = w
w_f = np.array([w_1, w_2])

def f(w):
    return np.dot(d.T, np.dot(A2, w))
def f_1(x, w):
    if x == 0:
        return f(w[0])
    elif x == 1:
        return f(w[1])

# Trova l'argomento che minimizza la funzione per il primo vettore
result_1 = minimize_scalar(f_1, args=(w_f,), bounds=(0, 0), method='bounded')
arg_min_1 = result_1.x
print(arg_min_1)

# Trova l'argomento che minimizza la funzione per il secondo vettore
result_2 = minimize_scalar(f_1, args=(w_f,), bounds=(1, 1), method='bounded')
arg_min_2 = result_2.x
print(arg_min_2) 
# Confronta i risultati per determinare quale valore minimizza di più la funzione
if arg_min_1 < arg_min_2:
    # Il primo vettore minimizza di più la funzione
    print("Il primo vettore minimizza di più la funzione.")
    print("argmin1: {}".format(arg_min_1))
    w[t_n] = arg_min_1
elif arg_min_1 > arg_min_2:
    # Il secondo vettore minimizza di più la funzione
    print("Il secondo vettore minimizza di più la funzione.")
    print("argmin2: {}".format(arg_min_2))
    w[t_n] = arg_min_2
else:
    # Entrambi i valori sono uguali
    print("Entrambi i valori minimizzano la funzione allo stesso modo.")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [162]:
w_2 = w
f_w = []
f_w.insert(0, w_1)
f_w.insert(1, w_2)
f_w = [array.tolist() for array in f_w]
def f(w):
    return np.dot(d.T, np.dot(A2, w))
def update_weights(f_w):
    best_w = None
    min_value = float('inf')
    s = A2.shape[1]
    for c in range(len(f_w)):
        for _ in range(s):
            value = f(f_w[c])
            if value < min_value:
                min_value = value
                best_w = f_w[c]
    return best_w, min_value

In [163]:
best_w, v = update_weights(f_w)

In [164]:
print(best_w)

[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]


In [ ]:
def create_d_t(d, A, w):
    m = len(d)
    delta = np.sum(d * np.log(d)) + np.log(m)
    result = np.dot(d.T, np.dot(A, w))
    result += (1/m) * delta
    return result

In [ ]:
#set v, T parameters
v = 100
T = 5
#create all the variables that we need
E_t = []
E_t.insert(0, ej1)
lamb = []
lamb.insert(0, np.zeros(m))
for t in range(1, T):
    #create the distribution d_t
    t_n = t + 1
    d, result = minimize_expression(A1, w, n, v)
    print("d_t is {}".format(result))
    #obtain the hypothesis h_j+1 and e_j+1
    h= weak_learner(X_train,y_train,result)
    hj_next= weak_classifier.predict(X_test)  # Total number of hypotheses in the set H
    hj_next_index = np.argmax(hj_next)  # Find the index of the predicted hypothesis
    num_hypotheses = len(hj_next)  # Total number of hypotheses in the set H
    ej_next = encode_hypothesis(hj_1_index, num_hypotheses)
    E_t.insert(t_n, ej_next)
    print(len(ej_next))
    #compute the FW weight
    value_0 = np.dot(A1, (ej_next-w[t]))
    value_1 = np.dot(result.T, value_0)
    value_2 = np.dot(A1, ej_next - w[t])
    value_3 = norm(value_2, ord=np.inf)
    value = value_1 / value_3
    lamb.insert(t, np.clip(value, 0, 1))
    w_1= []
    r = (ej_next - w[t])
    w_1.insert(0, w[t] + (lamb[t]*r))
    print(w_1)
    #compute the secondary weight
    w_2 = []
    my_f = lambda d, A, w: np.dot(d.T, np.dot(A1, w))
    result = minimize(my_f, x0=d, args=(A1, w))
    w_2.append(result.x)
    print(w_2)
    #update the weight
    w_f = np.array([w_1, w_2])
    def f(w):
        return np.dot(d0.T, -np.dot(A, w))
    def f_1(x, w):
        if x == 0:
            return f(w[0])
        elif x == 1:
            return f(w[1])

    # Trova l'argomento che minimizza la funzione per il primo vettore
    result_1 = minimize_scalar(f_1, args=(w_f,), bounds=(0, 0), method='bounded')
    arg_min_1 = result_1.x
    print(arg_min_1)

    # Trova l'argomento che minimizza la funzione per il secondo vettore
    result_2 = minimize_scalar(f_1, args=(w_f,), bounds=(1, 1), method='bounded')
    arg_min_2 = result_2.x
    print(arg_min_2)
    # Confronta i risultati per determinare quale valore minimizza di più la funzione
    if arg_min_1 < arg_min_2:
        # Il primo vettore minimizza di più la funzione
        print("Il primo vettore minimizza di più la funzione.")
        print("argmin1: {}".format(arg_min_1))
        w[t_n] = arg_min_1
    elif arg_min_1 > arg_min_2:
        # Il secondo vettore minimizza di più la funzione
        print("Il secondo vettore minimizza di più la funzione.")
        print("argmin2: {}".format(arg_min_2))
        w[t_n] = arg_min_2
    else:
        # Entrambi i valori sono uguali
        print("Entrambi i valori minimizzano la funzione allo stesso modo.")